version: "3.5"
services:
    opensky-polling-data:
        image: "jluetolf/opensky-polling-data"
        ports:
            - 50000:50000
        environment:
            PUBLIC_IP: ${PUBLIC_IP}
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3

    opensky-enrich-data:
        image: "jluetolf/opensky-enrich-data"
        ports:
            - 50100:50100
        environment:
            PUBLIC_IP: ${PUBLIC_IP}
        depends_on:
            - opensky-polling-data

    opensky-store-cassandra:
        image: "jluetolf/opensky-store-cassandra"
        ports:
            - 50200:50200
        environment:
            PUBLIC_IP: ${PUBLIC_IP}
        depends_on:
            - opensky-enrich-data
            - cassandra-1
        restart: unless-stopped

    opensky-store-opensearch:
        image: "jluetolf/opensky-store-opensearch"
        ports:
            - 50300:50300
        environment:
            PUBLIC_IP: ${PUBLIC_IP}
        depends_on:
            - opensky-enrich-data
            - opensearch-1
           
    opensky-test-application:
        image: "jluetolf/opensky-test-application"
        ports:
            - 51000:51000
        environment:
            PUBLIC_IP: ${PUBLIC_IP}
